name: Lint Code Base

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    container:
      image: docker://marcospariveda/python-linting:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint with pylint
        run: |
          make pylint
      - name: Check with flake8
        run: |
          make check
