name: Lint and verify builds

on:
  push:
    branches-ignore: []
  pull_request:
    branches: [master]

jobs:
  run-super-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          VALIDATE_CLOUDFORMATION: true
          VALIDATE_JSON: true

