name: Lint Python Code

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check for Pthon files
        shell: bash {0}
        # Give an id to the step, so we can reference it later
        id: check_file_changed
        run: |
          SOURCEDIFF=$(git diff origin/master...HEAD --name-only --diff-filter=d | grep  -E "(.py)") &&
          echo "SOURCEDIFF=$SOURCEDIFF" >> $GITHUB_OUTPUT
      - name: Set up Python 3.8
        if: steps.check_file_changed.outputs.SOURCEDIFF
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        if: steps.check_file_changed.outputs.SOURCEDIFF
        run: |
          make install
      - name: Lint with pylint
        if: steps.check_file_changed.outputs.SOURCEDIFF
        run: |
          make pylint
      - name: Check with flake8
        if: steps.check_file_changed.outputs.SOURCEDIFF
        run: |
          make check
