name: Lint Python Code

on:
  pull_request:
    branches: [master]

jobs:
  files_did_change:
    name: Detect files changed in PR
    runs-on: ubuntu-latest
    outputs:
      SOURCEDIFF: ${{ steps.check_file_changed.outputs.SOURCEDIFF }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - shell: bash {0}
        # Give an id to the step, so we can reference it later
        id: check_file_changed
        run: |
          SOURCEDIFF=$(git diff origin/master...HEAD --name-only --diff-filter=d | grep  -E "(.py$)")

  lint:
    name: Lint Python Files in PR
    runs-on: ubuntu-latest
    needs: files_did_change

    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          make install
      - name: Lint with pylint
        run: |
          make pylint
      - name: Check with flake8
        run: |
          make check
