name: JS Actions

on:
  issues:
    types: [labeled]

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        working-directory: ./.github/actions/joke-action
        run: npm install
      - name: ha-ha
        uses: ./.github/actions/joke-action
